# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NItj2_GAePC593udWOJcRRotQBT0Jiik
"""

def calcular_edad_futura(edad_actual):
    """Calcula la edad del usuario en una década."""
    edad_futura = edad_actual + 10
    return edad_futura

# Solicitar el nombre y la edad del usuario
nombre = input("Por favor, introduzca su nombre: ")
edad_actual = int(input("Por favor, introduzca su edad: "))

# Calcular la edad futura
edad_futura = calcular_edad_futura(edad_actual)

# Mostrar el resultado al usuario
print(f"Estimado {nombre}, en una década su edad será de {edad_futura} años.")
