# -*- coding: utf-8 -*-
"""S3_AlejandroMoyano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMb009erXFa6U-cMJtKdSoHoCnTkvL3L
"""

def calcular_descuento(total):
    """Calcula el descuento basado en el total de la venta."""
    if total < 50000:
        descuento = total * 0.07
    else:
        descuento = total * 0.12
    return int(descuento)

def main():
    # Inicializar variables
    total = 0

    while True:
        # Solicitar el precio del producto al usuario
        try:
            precio = int(input("Ingrese el precio del producto (ingrese 0 para finalizar): "))
        except ValueError:
            print("Entrada invalida. Por favor, ingrese un numero valido.")
            continue

        # Verificar si el usuario ha terminado de ingresar precios
        if precio == 0:
            break

        # Agregar el precio al total
        total += precio

    # Calcular el descuento
    descuento = calcular_descuento(total)

    # Calcular el monto a pagar
    monto_a_pagar = total - descuento

    # Mostrar los resultados
    print(f"Total de la venta sin descuentos: ${total:,}")
    print(f"Monto de descuento: ${descuento:,}")
    print(f"Monto a pagar con descuentos aplicados: ${monto_a_pagar:,}")

# Ejecutar la función principal
main()
